/*
 * Day09 - SQL 基礎
 * 
 * 學習重點：
 * 1. 建立資料表
 * 2. Primary Key
 * 3. Foreign Key
 * 4. INSERT / UPDATE / DELETE /SELECT
 */


-- 1. 建立 STUDENT 表

CREATE TABLE STUDENT (
    SNO CHAR(10),
    SNAME CHAR(10)
);


-- 2. 建立 GRADE 表

CREATE TABLE GRADE (
    GID INT,
    SNO CHAR(10),
    COURSE CHAR(10),
    SCORE INT
);


-- 3. 新增資料 (INSERT)

INSERT INTO STUDENT VALUES ('1001','JOHN');
INSERT INTO STUDENT VALUES ('1002','MARY');
INSERT INTO STUDENT VALUES ('1003','TOM');
INSERT INTO STUDENT VALUES ('1004','JERRY');


INSERT INTO GRADE VALUES (1,'1001','CHI',70);
INSERT INTO GRADE VALUES (2,'1002','ENG',80);
INSERT INTO GRADE VALUES (3,'1002','MATH',90);
INSERT INTO GRADE VALUES (4,'1003','CHI',80);
INSERT INTO GRADE VALUES (5,'1003','ENG',70);
INSERT INTO GRADE VALUES (6,'1003','MATH',60);
INSERT INTO GRADE VALUES (7,'1005','CHI',50);

-- 4. INSERT

INSERT INTO STUDENT VALUES ('1006','MARK');
INSERT INTO STUDENT VALUES ('1007','MARIA');

-- 5. UPDATE 

UPDATE STUDENT
SET SNAME='ANGEL'
WHERE SNO='1007';

-- 6. DELETE 

DELETE FROM STUDENT
WHERE SNO='1007';



-- 7. 條件查詢

SELECT *
FROM GRADE
WHERE SCORE >= 80;

-- 8. Primary Key

ALTER TABLE STUDENT
ADD PRIMARY KEY (SNO);

-- 9. Foreign Key

ALTER TABLE GRADE
ADD FOREIGN KEY (SNO)
REFERENCES STUDENT(SNO);

-- 10. 作業練習

INSERT INTO STUDENT VALUES ('1234','林志玲');

UPDATE STUDENT
SET SNAME='王建民'
WHERE SNO='1234';

DELETE FROM STUDENT
WHERE SNO='1234';